# Generated by Django 4.2.16 on 2024-09-07 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0007_rename_user_id_user_uid_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
