# Generated by Django 4.2.16 on 2024-09-07 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0009_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
