# Generated by Django 4.2.16 on 2024-09-10 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0011_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='date_cr',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/gato.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
