# Generated by Django 4.2.16 on 2024-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0017_alter_user_date_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_cr',
            field=models.DateField(auto_now_add=True),
        ),
    ]
