# Generated by Django 4.2.16 on 2024-09-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0018_alter_user_date_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
