# Generated by Django 4.2.16 on 2024-09-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0021_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
