# Generated by Django 4.2.16 on 2024-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0033_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='dash_env/dash_env/images'),
        ),
    ]
