# Generated by Django 4.2.16 on 2024-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0040_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_mode', models.CharField(max_length=200)),
                ('first_p_id', models.IntegerField(default=0)),
                ('second_p_id', models.IntegerField(default=0)),
            ],
        ),
    ]
