# Generated by Django 4.2.16 on 2024-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0041_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match_mode',
        ),
        migrations.AddField(
            model_name='matches',
            name='first_p_res',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='second_p_res',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
