# Generated by Django 4.2.16 on 2024-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0042_remove_matches_match_mode_matches_first_p_res_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='first_p_res',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='second_p_res',
        ),
        migrations.AddField(
            model_name='user',
            name='user_result',
            field=models.IntegerField(default=0),
        ),
    ]
