# Generated by Django 4.2.16 on 2024-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0045_alter_user_profile_picture_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='aa', max_length=200),
        ),
    ]
