# Generated by Django 4.2.16 on 2024-09-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0047_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
