# Generated by Django 4.2.16 on 2024-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0048_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
