# Generated by Django 4.2.16 on 2024-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0049_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default="Hi, I'm new here", max_length=30),
        ),
    ]
