version: '3'

services:
  match_history:
    build: ./match_history
    image: match_history
    container_name: match_history
    ports:
      - "8000:8000"
    volumes:
      - matches-volume:/match_history

volumes:
  matches-volume:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdel-ou/Desktop/lol/match_history"