version: '3'

services:
  match_history:
    build: ./match_history
    image: match_history
    container_name: match_history
    ports:
      - "8000:8000"
    volumes:
      - matches-volume:/match_history
  game_backend:
    build: ./gamebackend
    image: gamebackend
    container_name: gamebackend
    ports:
      - "8001:8001"
    volumes:
      - game-volume:/gamebackend
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  matches-volume:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdelmajid/Desktop/lol/match_history"
  game-volume:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdelmajid/Desktop/lol/gamebackend"
  