version: '3'

services:
  match_history:
    build: ./match_history
    image: match_history
    container_name: match_history
    ports:
      - "8000:8000"
    volumes:
      - matches-volume:/match_history
  authentication:
    build: ./authentication
    image: authentication
    container_name: authentication
    ports:
      - "8001:8001"
    volumes:
      - authentication-volume:/authentication
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  gamebackend:
    build: ./gamebackend
    image: gamebackend
    container_name: gamebackend
    ports:
      - "8002:8002"
    volumes:
      - game:/gamebackend
    depends_on:
      - redis
      - match_history
      - authentication

volumes:
  matches-volume:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdelmajid/Desktop/lol/match_history"
  authentication-volume:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdelmajid/Desktop/lol/authentication"
  game:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/abdelmajid/Desktop/lol/gamebackend"
  